### ISSUE TITLE
Allow %placeholders% in a list - [merged]

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-config-parser#26]
In GitLab by @dbeltrankyl on Aug 13, 2024, 10:53

_Merges dates -> main_

#https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1045 #https://earth.bsc.es/gitlab/es/autosubmit/-/issues/1288 https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/470

What does this branch is to allow AS placeholders on lists like in this example:
```yaml
ROCRATE:
  INPUT:
    - name: "DATELIST"
      value: "%EXPERIMENT.DATELIST%"
      additionalType: "String"
      valueRequired: "True"
```
